language: perl
perl:
  - "5.8"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.24"
matrix:
  include:
    - perl: "5.20"
      env: DB=MySQL VERSION=4.1.22
    - perl: "5.20"
      env: DB=MySQL VERSION=5.0.15
    - perl: "5.20"
      env: DB=MySQL VERSION=5.0.96
    - perl: "5.20"
      env: DB=MySQL VERSION=5.1.30
    - perl: "5.20"
      env: DB=MySQL VERSION=5.1.72
    - perl: "5.20"
      env: DB=MySQL VERSION=5.5.8
    - perl: "5.20"
      env: DB=MySQL VERSION=5.5.47
    - perl: "5.20"
      env: DB=MySQL VERSION=5.5.54
    - perl: "5.20"
      env: DB=MySQL VERSION=5.6.10
    - perl: "5.20"
      env: DB=MySQL VERSION=5.6.30
    - perl: "5.20"
      env: DB=MySQL VERSION=5.6.35
    - perl: "5.20"
      env: DB=MySQL VERSION=5.7.8-rc
    - perl: "5.20"
      env: DB=MySQL VERSION=5.7.17
    - perl: "5.20"
      env: DB=MySQL VERSION=8.0.0-dmr
    - perl: "5.20"
      env: DB=MariaDB VERSION=5.5.40
    - perl: "5.20"
      env: DB=MariaDB VERSION=5.5.47
    - perl: "5.20"
      env: DB=MariaDB VERSION=5.5.54
    - perl: "5.20"
      env: DB=MariaDB VERSION=10.0.14
    - perl: "5.20"
      env: DB=MariaDB VERSION=10.0.29
    - perl: "5.20"
      env: DB=MariaDB VERSION=10.1.2
    - perl: "5.20"
      env: DB=MariaDB VERSION=10.1.8
    - perl: "5.20"
      env: DB=MariaDB VERSION=10.1.20
    - perl: "5.20"
      env: DB=MariaDB VERSION=10.2.0
    - perl: "5.20"
      env: DB=MariaDB VERSION=10.2.1
before_install:
  - if [ "$DB" = "MySQL" ]; then
      case "$VERSION" in
        4.1.*)       SANDBOX_URL=http://mysql.localhost.net.ar/Downloads/MySQL-4.1/mysql-standard-$VERSION-unknown-linux-gnu-x86_64-glibc23.tar.gz ;;
        5.0.[012]*)  SANDBOX_URL=https://downloads.mysql.com/archives/get/file/mysql-standard-$VERSION-linux-x86_64-glibc23.tar.gz ;;
        5.[01].*)    SANDBOX_URL=https://downloads.mysql.com/archives/get/file/mysql-$VERSION-linux-x86_64-glibc23.tar.gz ;;
        5.5.*)       SANDBOX_URL=https://dev.mysql.com/get/mysql-$VERSION-linux2.6-x86_64.tar.gz ;;
        5.[67].*)    SANDBOX_URL=https://dev.mysql.com/get/mysql-$VERSION-linux-glibc2.5-x86_64.tar.gz ;;
        8.0.*)       SANDBOX_URL=https://dev.mysql.com/get/mysql-$VERSION-linux-glibc2.12-x86_64.tar.gz ;;
        *)           echo "Unsupported MySQL version '$VERSION'"; exit 1 ;;
      esac ;
      SANDBOX_FILE="$HOME/$(basename "$SANDBOX_URL")" ;
    elif [ "$DB" = "MariaDB" ]; then
      SANDBOX_URL=https://downloads.mariadb.org/interstitial/mariadb-$VERSION/bintar-linux-x86_64/mariadb-$VERSION-linux-x86_64.tar.gz/from/http%3A//ftp.hosteurope.de/mirror/archive.mariadb.org/ ;
      SANDBOX_FILE="$HOME/mariadb-$VERSION-linux-x86_64.tar.gz" ;
    elif [ -n "$DB" ]; then
      echo "Unsupported DB '$DB'"; exit 1 ;
    fi
  - if [ -n "$DB" ]; then
      export SANDBOX_HOME="$HOME/sandbox" ;
      export SANDBOX_BINARY="$SANDBOX_HOME/binary" ;
      wget "$SANDBOX_URL" -O "$SANDBOX_FILE" || exit 1 ;
    fi
  - sudo apt-get update -qq
  - if [ -n "$DB" ]; then
      sudo apt-get install -qq libaio-dev libnuma-dev libjemalloc-dev || exit 1 ;
      sudo apt-get remove -qq mysql-client mysql-client-5.5 mysql-client-core-5.5 mysql-common mysql-server mysql-server-5.5 mysql-server-core-5.5 libmysqlclient-dev libmysqlclient18 || exit 1 ;
    else
      sudo apt-get install -qq libmysqlclient-dev libmysqld-dev libwrap0-dev || exit 1 ;
    fi
  - perlbrew install-cpanm -f
install:
  - cpanm --quiet DBI Test::Pod Test::Deep Test::DistManifest Proc::ProcessTable Devel::CheckLib
  - if [ -n "$DB" ]; then
      cpanm --quiet MySQL::Sandbox || exit 1 ;
      make_sandbox --export_binaries "$SANDBOX_FILE" -- --sandbox_port 3310 --sandbox_directory msb --no_confirm || exit 1 ;
      printf '%s\n%s\n' '#!/bin/sh' 'exec "$SANDBOX_HOME/msb/my" sql_config "$@"' > "$SANDBOX_HOME/msb/mysql_config" || exit 1 ;
      chmod +x "$SANDBOX_HOME/msb/mysql_config" || exit 1 ;
    fi
  - export RELEASE_TESTING=1
script:
  - if [ -n "$DB" ]; then
      perl Makefile.PL --mysql_config="$SANDBOX_HOME/msb/mysql_config" --testuser=msandbox --testpassword=msandbox --testhost=127.0.0.1 --testport=3310 && make disttest || exit 1;
    else
      perl Makefile.PL && make disttest || exit 1 ;
      perl Makefile.PL --force-embedded && make disttest || exit 1 ;
    fi
