language: perl
perl:
  - "5.8"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libmysqlclient-dev
 - perlbrew install-cpanm -f
before_script:
  - mysql -e 'create database myapp_test;'
install:
  - cpanm DBI Test::Pod Test::Deep Test::DistManifest Proc::ProcessTable
env:
  - EXTENDED_TESTING=1
  - RELEASE_TESTING=1
  - DBD_MYSQL_TESTDB=myapp_test
  - DBD_MYSQL_TESTUSER=travis
script: "perl Makefile.PL && make disttest"
